<?php
$form->prepare();

$escapeHtml = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Sru Srw Map List'), 1, $this->translate('Sru Srw Map Maker')); ?>

<table style="border: solid 1px; width: 60%;">
    <tr>
        <th style="border-right: solid 1px; width:70px;text-align:right;">ID</th>
        <th style="border-right: solid 1px";>local property</th>
        <th>standard property</th>
    </tr>
<?php foreach ($maps as $map): ?>
    <tr>
        <td style="border-right: solid 1px; border-top: solid 1px; width:470px;text-align:right;"><?php echo $map->id(); ?></td>
        <td style="border-right: solid 1px; border-top: solid 1px;"><?php echo $map->localProperty(); ?></td>
        <td style="border-top: solid 1px;"><?php echo $map->standardProperty(); ?></td>
    </tr>
<?php endforeach;?>
</table>
