<?php
$form->prepare();

$escapeHtml = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate(' Srw Map Import'), 1, $this->translate('Sru Srw Maker')); ?>

<?php echo $this->form()->openTag($form); ?>
<fieldset id='page-actions'>
    <button type="submit"><?php echo $this->translate('Submit'); ?></button>
</fieldset>
<?php echo $this->formCollection($form, false); ?>

<?php echo $this->form()->closeTag($form); ?>
